export const surpriseMePrompts = [
  "Un sillón con forma de aguacate",
  "Un óleo surrealista de Salvador Dalí con un gato jugando a las damas",
  "Osos de peluche comprando en Japón, ukiyo-e",
  "Un óleo de Matisse de un robot humanoide jugando al ajedrez",
  "Científico loco panda mezclando productos químicos espumosos, arte digital",
  "Una macrofotografía de 35 mm de dos ratones en Hawai, cada uno lleva un diminuto bañador y una pequeña tabla de surf, arte digital",
  "Render en 3D de un bonito pez tropical en un acuario sobre fondo azul oscuro, arte digital",
  "Un astronauta descansando en un resort tropical en el espacio, vaporwave",
  "Un retrato al óleo de un carpincho con ropajes reales medievales y una corona ornamentada sobre un fondo oscuro",
  "Una vidriera que representa una hamburguesa con patatas fritas",
  "Un dibujo a lápiz y acuarela de una luminosa ciudad del futuro con coches voladores",
  "Un salón interior iluminado por el sol con una piscina de agua clara y otra piscina de agua translúcida rosa pastel, junto a un gran ventanal, arte digital",
  "Un shiba inu adivino leyendo tu destino en una hamburguesa gigante, arte digital",
  "Una nutria marina con un pendiente de perla de Johannes Vermeer",
  "Un dibujo al óleo de un gato molesto en una nave espacial",
  "Un cuadro de un zorro al estilo de 'La noche estrellada'",
  "Un plato de sopa que parece un monstruo, tejido con lana",
  "Un robot de peluche sentado contra una pared amarilla",
  "Una puesta de sol estilo synthwave sobre el agua del mar, arte digital",
  "Dos torres futuristas con una pasarela cubierta de exuberante vegetación, arte digital",
  "Un globo aerostático con los colores del arco iris sobrevolando un lago reflectante",
  "Una portada de cómic de un superhéroe con auriculares",
  "Una explosión centrada de polvo de colores sobre un fondo negro",
  "Una foto de un perro samoyedo con la lengua fuera abrazando a un gato siamés blanco",
  'Una foto de un monstruo de pelaje blanco de pie en una habitación morada',
  "Una foto de la escultura de David de Miguel Ángel con auriculares haciendo dj",
  'Un Samurai montando a caballo en Marte, lomografía',
  'Un moderno y elegante Cadillac circula por la autopista Gardiner con el centro de Toronto al fondo, con un destello de lente, fotografía de 50 mm',
  'Una fotografía realista de una mujer joven con ojos azules y pelo rubio',
  "Un hombre delante de una puerta estelar a otra dimensión",
  "Bob Esponja en el Proyecto de la Bruja de Blair",
  "Un velociraptor trabajando en un puesto de perritos calientes, lomografía",
  "Un hombre caminando de noche por las bulliciosas calles de Kowloon, iluminado por muchos letreros luminosos de neón, objetivo de 50 mm",
  'Una barbacoa que está viva, al estilo de una película de animación de Pixar',
  "Un club de baile futurista con cyborgs y luces de neón",
  "El anime japonés perdido de Star Wars 1990",
  "Una hamburguesa con forma de cubo de Rubik, fotografía profesional de alimentos",
  "Un erizo Synthwave, Blade Runner Cyberpunk",
  "Un astronauta encuentra una forma de vida alienígena en un planeta lejano, fotografía",
  "Un dinosaurio explorando Ciudad del Cabo, fotografía",
  "Un hombre enamorado de su ordenador, arte digital",
  "Fotografía de un cyborg explorando Tokio por la noche, lomografía",
  "Drácula caminando por las calles de Nueva York en los años 20, fotografía en blanco y negro",
  "Avión Synthwave",
  'Un hombre deambula por las calles lluviosas de Tokio, con brillantes letreros de neón, 50mm',
  "Un transbordador espacial sobrevolando Ciudad del Cabo, arte digital",
];